name = input("Enter Your Name, and press enter:")
drink = input("Enter your favorite drink, and press enter:")
adj1 = input("Enter an adjective, and press enter:")
noun1 = input("Enter a noun, and press enter:")
verb1 = input("Enter a verb, and press enter:") 
color1 = input("Enter a color, and press enter:")
celeb1 = input("Enter the name of a celebrity, and press enter:")
planet = input("Enter the name of an imaginary planet, and press enter:") 
animal = input("Enter the name of your favorite animal in plural tense, and press enter:") 
verb2 = input("Enter a verb, and press enter:") 
noun2 = input("Enter a plural noun, and press enter:") 
adj2 = input("Enter an adjective, and press enter:") 
athlete = input("Enter the name of an athlete, and press enter:") 
verb3 = input("Enter a present participle verb (ing), and press enter:") 
celeb2 = input("Enter the name of a celebrity, and press enter:") 
noun3 = input("Enter a plural noun, and press enter:") 

story = 'In a galaxy far far away ' + name + ', a powerful Jedi master, enjoyed a glass of ' + drink + ' in his home. Suddenly a '  + adj1 + ' Anakin Skywalker runs into the room to grab his beloved ' + noun1 + '. Suddenly the feared Sith lord Orly teleports into the room.' + ' In typical Orly manner, she uses the force to ' + verb1 + ' in a speed never seen before. Enraged, ' + name + ' ignites a '  + color1 + ' lightsaber to help save the universe. All of a sudden, ' + celeb1 + ', the sith apprentice of Orly, ignites a flaming red lightsaber ' + 'Anakin and ' + name + ' begin to duel Orly and ' + celeb1 + '. After several minutes of intense fighting, Orly chops off an arm of Anakin' + 'Desperate and armless, Anakin Skywalker, The Chosen One, uses the force to teleport everyone to the planet ' + planet + '. The mysterious' + ' planet is full of several ' + '. Instead of enjoying the beautiful scenery, the fight continued. Both sides were evenlly matched, but' + ' anakin realized he needed 2 arms to win the fight. To regenerate his arm, Anakin ' + verb2 + ' next to a fluffy koala. After regaining his' + ' arm, Anakin killed the sith apprentice. Orly became very ' + adj2 + '. A wise  ' + athlete + ' used the conflict to become rich ' + ' from war profiteering. However, the vicious Orly became enraged and killed everone in her sight except ' + name + '. After seeing the' + ' lifeless body of Anakin Skywalker, ' + name + ' started ' + verb3 + ' to gain an advantage. However, it was not enough. ' + name + ' realized that the only way to decide the outcome of the duel was to challenge Orly to a Fortnite 1 v 1. The game became the duel of' + ' the century, but Orly lost because she forgot to deploy her glider. As a reward for defeating the sith, ' + celeb2 + ' gave ' + name + ' a lifetime supply of ' + noun3 + '. Everyone in the galaxy lived happily ever after.'

print(story)